version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.10
    container_name: elasticsearch
    ports: 
      - "9200:9200"
    environment:
      - http.cors.enabled=true
      - http.cors.allow-origin=http://localhost:3000,http://127.0.0.1:1358
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-credentials=true
    
  kibana:
    image: docker.elastic.co/kibana/kibana:6.8.10
    container_name: kibana
    ports: 
      - "5601:5601"
    depends_on: ['elasticsearch']