export const CLEAR_SESSION = 'CLEAR_SESSION'
export const SET_SESSION = 'SET_SESSION'

export const API = "API";
export const API_START = "API_START";
export const API_END = "API_END";
export const ACCESS_DENIED = "ACCESS_DENIED";
export const API_ERROR = "API_ERROR";

export const SET_USER = "SET_USER";

export const SET_USER_BOARD = "SET_USER_BOARD";
export const SET_USER_BOARDS = "SET_USER_BOARDS";
export const USER_BOARD_CREATED="USER_BOARD_CREATED";
export const USER_BOARD_UPDATED="USER_BOARD_UPDATED";
export const USER_BOARD_DELETED="USER_BOARD_DELETED";


export const SET_USER_SESSION='SET_USER_SESSION';
export const USER_SESSION_CLEARED = 'USER_SESSION_CLEARED';
export const SET_USER_SESSIONS = "SET_USER_SESSIONS";
export const SESSION_CREATED = "SESSION_CREATED";
export const DELETE_USER_SESSION = "DELETE_USER_SESSION";
export const USER_SESSION_UPDATED="USER_SESSION_UPDATED"
export const USER_SESSION_DELETED="USER_SESSION_DELETED"

export const SHAPERS_LOADED="SHAPERS_LOADED";

export const BOARDS_LOADED="BOARDS_LOADED";

export const USER_BOARD_IMAGES_LOADED="USER_BOARD_IMAGES_LOADED";

export const USER_BOARD_IMAGES_CREATED="USER_BOARD_IMAGES_CREATED";

export const USER_BOARD_IMAGE_DELETED = "USER_BOARD_IMAGE_DELETED"

export const USER_SESSION_LOADED="USER_SESSION_LOADED";

export const USER_SESSION_IMAGES_LOADED="USER_SESSION_IMAGES_LOADED";

export const USER_SESSION_IMAGES_CREATED="USER_SESSION_IMAGES_CREATED";

export const USER_SESSION_IMAGE_DELETED = "USER_SESSION_IMAGE_DELETED";

export const USER_LOGGED_IN="USER_LOGGED_IN";

export const USER_LOADED="USER_LOADED";

export const USER_IMAGE_UPDATED="USER_IMAGE_UPDATED";